repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.4
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.5.3
    hooks:
      # Update the uv lockfile
      - id: uv-lock
