[project]
name = "e3dc"
version = "0.1.0"
authors = [
    {name = "Francesco Santini", email = "francesco.santini@gmail.com"},
    {name = "Christopher Banck", email = "christopher@banck.net"},
]
description = "E3/DC client for python"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = [
    "py3rijndael",
    "python-dateutil",
    "requests>=2.32.3",
    "tzlocal",
    "websocket-client",
]

[dependency-groups]
dev = [
    "ruff >= 0.8.1",
    "pytest >= 8.3.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/e3dc"]

[tool.ruff]
exclude = ["src"]
